# DATA
data_name: "PA100K"
root_dir: "./data/PA-100K/release_data/release_data"
group_index: [7,8,13,14,15,16,17,18,19,20,21,22,23,24,25,9,10,11,12,1,2,3,0,4,5,6]
num_per_group: [2, 6, 6, 1, 4, 3, 1, 3]

# data_path: "./data/annotations/phase1/train/train.csv"
train_batch_size: 128
test_batch_size: 128

# Training
learning_rate: 0.0001
num_epochs: 30
num_attr: 26
use_multi_task: False

# loss
loss: bce_loss
sample_weight: True
scale: 1

# Model
backbone: swin_base_patch4_window7_224

seed: 42